name: Build Realtek r8152 Driver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential linux-headers-$(uname -r) fakeroot

    - name: Build driver
      run: |
        cd r8152-2.18.1
        make clean
        make

    - name: Create IPK package
      run: |
        mkdir -p ipk_package/r8152-2.18.1/CONTROL
        mkdir -p ipk_package/r8152-2.18.1/lib/modules/$(uname -r)/kernel/drivers/net/usb/
        cp r8152.ko ipk_package/r8152-2.18.1/lib/modules/$(uname -r)/kernel/drivers/net/usb/

        cat <<EOF > ipk_package/r8152-2.18.1/CONTROL/control
        Package: r8152
        Version: 2.18.1
        Architecture: $(dpkg --print-architecture)
        Maintainer: Your Name <your.email@example.com>
        Description: Realtek r8152 2.5G USB Ethernet driver
        EOF

        cat <<EOF > ipk_package/r8152-2.18.1/CONTROL/postinst
        #!/bin/sh
        depmod
        modprobe r8152
        EOF
        chmod +x ipk_package/r8152-2.18.1/CONTROL/postinst

        cd ipk_package
        tar --owner=0 --group=0 -czvf data.tar.gz -C r8152-2.18.1 .
        tar --owner=0 --group=0 -czvf control.tar.gz -C r8152-2.18.1/CONTROL .
        echo "2.0" > debian-binary
        ar rcs r8152-2.18.1.ipk control.tar.gz data.tar.gz debian-binary

    - name: Upload IPK package
      uses: actions/upload-artifact@v2
      with:
        name: r8152-2.18.1-ipk
        path: ipk_package/r8152-2.18.1.ipk

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v2.18.1
        release_name: Realtek r8152 Driver v2.18.1
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ipk_package/r8152-2.18.1.ipk
        asset_name: r8152-2.18.1.ipk
        asset_content_type: application/octet-stream
