name: Build Realtek r8152 Driver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential linux-headers-$(uname -r) fakeroot

    - name: Build driver
      run: |
        cd r8152-2.18.1
        make clean
        make

    - name: Create IPK package
      run: |
        mkdir -p ipk_package/r8152-2.18.1/CONTROL
        mkdir -p ipk_package/r8152-2.18.1/lib/modules/$(uname -r)/kernel/drivers/net/usb/

        # 找到生成的 r8152.ko 文件并复制到目标目录
        find . -name 'r8152.ko' -exec cp {} ipk_package/r8152-2.18.1/lib/modules/$(uname -r)/kernel/drivers/net/usb/ \;

        cat <<EOT > ipk_package/r8152-2.18.1/CONTROL/control
        Package: r8152
        Version: 2.18.1
        Description: Realtek r8152 2.5G USB Ethernet driver
        Maintainer: Your Name <your.email@example.com>
        Architecture: $(uname -m)
        EOT

        cat <<EOT > ipk_package/r8152-2.18.1/CONTROL/postinst
        #!/bin/sh
        depmod
        modprobe r8152
        EOT
        chmod +x ipk_package/r8152-2.18.1/CONTROL/postinst

        cd ipk_package
        tar -czvf ../r8152-2.18.1.ipk r8152-2.18.1

    - name: Upload IPK package
      uses: actions/upload-artifact@v3
      with:
        name: r8152-2.18.1-ipk
        path: r8152-2.18.1.ipk

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v2.18.1
        release_name: Realtek r8152 Driver v2.18.1
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: r8152-2.18.1.ipk
        asset_name: r8152-2.18.1.ipk
        asset_content_type: application/octet-stream
